# Generated by Django 5.1.4 on 2025-11-10 03:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialsPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerVendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('business_type', models.CharField(choices=[('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('manufacturer', 'Manufacturer'), ('others', 'Others')], default='others', max_length=20, verbose_name='Business Type')),
                ('entity_type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor')], default='customer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer/Vendor',
                'verbose_name_plural': ' Customers/Vendors',
            },
        ),
        migrations.CreateModel(
            name='ARInvoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], db_index=True, default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'entity_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='ar_invoices', to='uniworlderp.customervendor')),
            ],
            options={
                'verbose_name': ' AR Invoice',
                'verbose_name_plural': ' AR Invoices',
            },
        ),
        migrations.CreateModel(
            name='CustomerVendorAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='customer_vendor_attachments/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='uniworlderp.customervendor')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer/Vendor Attachment',
                'verbose_name_plural': 'Customer/Vendor Attachments',
            },
        ),
        migrations.CreateModel(
            name='MaterialsPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='uniworlderp.materialspurchase')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description (Pack Size)')),
                ('category', models.CharField(choices=[('Chemical', 'Chemical'), ('RawMaterials', 'Raw Materials'), ('Others', 'Others')], default='Others', help_text='Select a category for the product.', max_length=50)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sales Price')),
                ('unit', models.CharField(choices=[('PC', 'PC'), ('CTN', 'CTN'), ('TIN', 'TIN'), ('Others', 'Others')], default='PC', max_length=10, verbose_name='Unit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Product Code')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the product is active and available.')),
                ('barcode', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Stock level at which reorder is required.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount amount for the product.', max_digits=10, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ARInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('ar_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='uniworlderp.arinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniworlderp.product')),
            ],
            options={
                'verbose_name': 'AR Invoice Item',
                'verbose_name_plural': 'AR Invoice Items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('delivery_status', models.CharField(choices=[('P', 'Pending'), ('R', 'Received')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(limit_choices_to={'entity_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='uniworlderp.customervendor')),
            ],
            options={
                'verbose_name': ' Purchase Order',
                'verbose_name_plural': ' Purchase Orders',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniworlderp.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='uniworlderp.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
            },
        ),
        migrations.CreateModel(
            name='SalesEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('sales_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_achieved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='sales_employee_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_employee_owner', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' Sales Employee',
                'verbose_name_plural': 'Sales Employees',
            },
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='sales_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_invoices', to='uniworlderp.salesemployee'),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('delivery_status', models.CharField(choices=[('P', 'Pending'), ('D', 'Delivered')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount to be subtracted from subtotal', max_digits=12)),
                ('shipping', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping amount to be added to subtotal after discount', max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='uniworlderp.customervendor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to=settings.AUTH_USER_MODEL)),
                ('sales_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='uniworlderp.salesemployee')),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
            },
        ),
        migrations.CreateModel(
            name='ReturnSales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('return_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to='uniworlderp.salesemployee')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='uniworlderp.salesorder')),
            ],
            options={
                'verbose_name': 'Sales Return',
                'verbose_name_plural': 'Sales Returns',
            },
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='sales_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='uniworlderp.salesorder'),
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('Unit_discount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount amount per unit for the product.', max_digits=10, null=True)),
                ('total_discount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount amount for the product.', max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniworlderp.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='uniworlderp.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnSalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('return_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='uniworlderp.returnsales')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='uniworlderp.salesorderitem')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJ', 'Adjustment'), ('RET', 'Return')], max_length=3)),
                ('quantity', models.IntegerField()),
                ('previous_stock', models.PositiveIntegerField(default=0, help_text='Stock quantity before the transaction')),
                ('current_stock', models.PositiveIntegerField(default=0, help_text='Stock quantity after the transaction')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='uniworlderp.product')),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
            },
        ),
        migrations.AddIndex(
            model_name='customervendor',
            index=models.Index(fields=['name', 'email', 'entity_type'], name='uniworlderp_name_af32bd_idx'),
        ),
        migrations.AddIndex(
            model_name='customervendorattachment',
            index=models.Index(fields=['customer_vendor', 'file_type'], name='uniworlderp_custome_8c7aec_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'price'], name='uniworlderp_name_214642_idx'),
        ),
        migrations.AddIndex(
            model_name='arinvoiceitem',
            index=models.Index(fields=['ar_invoice', 'product'], name='uniworlderp_ar_invo_3a1a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date', 'delivery_status'], name='uniworlderp_order_d_612de3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['purchase_order', 'product'], name='uniworlderp_purchas_1cf69c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_date', 'delivery_status'], name='uniworlderp_order_d_1c3235_idx'),
        ),
        migrations.AddIndex(
            model_name='returnsales',
            index=models.Index(fields=['return_date'], name='uniworlderp_return__771b81_idx'),
        ),
        migrations.AddIndex(
            model_name='arinvoice',
            index=models.Index(fields=['invoice_date', 'due_date', 'payment_status'], name='uniworlderp_invoice_2a6e54_idx'),
        ),
        migrations.AddConstraint(
            model_name='arinvoice',
            constraint=models.UniqueConstraint(fields=('sales_order',), name='unique_sales_order_invoice'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['product', 'transaction_type', 'transaction_date'], name='uniworlderp_product_8786c7_idx'),
        ),
    ]
